name = "TestForecasts"
uuid = "95d863b1-a657-4c1d-b29b-2e3b0a0dd124"
version = "0.1.0"
authors = ["lipiecki <arkadiusz.lipiecki@pwr.edu.pl>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.25.120"
LinearAlgebra = "1.12.0"
